In [1]:
from utils import *
from batchAQUA_general import *
import numpy as np


In [2]:
spikes = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0]])
I_inj = np.array([[0, 0 ,0, 0 ,0 ,0, 0],
                  [1, 1, 1, 1, 1, 1, 1]])

STA(spikes, I_inj, window = 3)

In [3]:
X = np.arange(30)

Y = embed(X, 5)

print(Y)

[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  5.]
 [ 2.  3.  4.  5.  6.]
 [ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]
 [ 5.  6.  7.  8.  9.]
 [ 6.  7.  8.  9. 10.]
 [ 7.  8.  9. 10. 11.]
 [ 8.  9. 10. 11. 12.]
 [ 9. 10. 11. 12. 13.]
 [10. 11. 12. 13. 14.]
 [11. 12. 13. 14. 15.]
 [12. 13. 14. 15. 16.]
 [13. 14. 15. 16. 17.]
 [14. 15. 16. 17. 18.]
 [15. 16. 17. 18. 19.]
 [16. 17. 18. 19. 20.]
 [17. 18. 19. 20. 21.]
 [18. 19. 20. 21. 22.]
 [19. 20. 21. 22. 23.]
 [20. 21. 22. 23. 24.]
 [21. 22. 23. 24. 25.]
 [22. 23. 24. 25. 26.]
 [23. 24. 25. 26. 27.]
 [24. 25. 26. 27. 28.]]


In [ ]:
spikes = np.array([[1, 4, 6, 9],
                   [2, 3, 5, 7]])

spike_train = binarise_spikes(spikes, dt = 1., N_iter = 10)


[[0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 1. 0. 1. 0. 0.]]
