In [1]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3, 4, 5, 0],
                [2, 4, 6, 8, 10, 12]])

diff = np.diff(arr, axis = 1)
print(diff)

unique, count = np.unique(diff, axis = 1, return_counts = True)
print(unique)
print(count)

[[ 1  1  1  1 -5]
 [ 2  2  2  2  2]]
[[-5  1]
 [ 2  2]]
[1 4]


In [6]:
import numpy as np

arr_str = np.array(["asnjbFSoinaso", "jhagsdfj nsdi", "FSniwene", "ajksdbhkjHFS"])

sub_arr = np.char.find(arr_str, 'FS') >= 0
print(sub_arr)

[ True False  True  True]
