In [2]:
import numpy as np
import pandas as pd

In [3]:

arr = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])

sub_arr = np.array([5, 5, 5])

print("ARRAY")
print(arr + sub_arr)


df = pd.DataFrame(arr, columns = ['A', 'B', 'C'])

print(df)

print(len(df))

ARRAY
[[6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4


In [ ]:
"""
import pickle

outfile = "CPA_test_data.pickle"
with open(outfile, 'rb') as file:
    data = pickle.load(file)

raw_data = data.iloc[:, -1].values

num_columns = len(data.columns) - 1
reshaped_data = raw_data.reshape(-1, num_columns)

new_df = pd.DataFrame(reshaped_data, columns = data.columns[:-1])

print(new_df)

#with open(outfile, 'wb') as file:
#    pickle.dump(new_df, file)
"""


ValueError: cannot reshape array of size 1600 into shape (6)