In [3]:
import numpy as np

In [4]:
I_inj = np.array([1, 2, 3, 4, 5])
N = 10

I = np.array([i*np.ones((N, 100)) for i in I_inj])

print(np.shape(I))
#print(I)

I = I.reshape(-1, 100)

print(np.shape(I))
print(I)


del I_inj, I


(5, 10, 100)
(50, 100)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]]
