In [2]:
import numpy as np

In [3]:
I_inj = np.array([1, 2, 3, 4, 5])
N = 10

I = np.array([i*np.ones((N, 100)) for i in I_inj])

print(np.shape(I))
#print(I)

I = I.reshape(-1, 100)

print(np.shape(I))
print(I)


del I_inj, I


(5, 10, 100)
(50, 100)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]]


In [5]:
arr1 = np.array([[0, 1, 2, 3, 4, 5],
                 [4, 5, 6, 7, 8, 9]])

print(np.diff(arr1, axis = 0))

print('- - - -')

print(np.diff(arr1, axis = 1))


for n, row in enumerate(arr1):
    print(row)

[[4 4 4 4 4 4]]
- - - -
[[1 1 1 1 1]
 [1 1 1 1 1]]
[0 1 2 3 4 5]
[4 5 6 7 8 9]
